### ISSUE TITLE
Scrape not moving at all sometimes

### ISSUE THREAD

**Issue by tehwateva** [DoctorD1501/JAVMovieScraper#35] opened 2015-01-21 13:07 UTC
I noticed the program freezes up often while scraping for info (usually at JavLibrary) and I have to force close it and re-do all the scraping again, is that a currently known issue?

**Comment by DoctorD1501** [comment] 2015-02-09 02:08
This is probably being caused by the fact that I don't have timeouts set on network calls, so they block  until the request completes. I'll have to figure out how to cleanly handle or detect the difference between a request just taking a long time and an actual request failure.

**Comment by DoctorD1501** [comment] 2015-05-16 04:34
Another thing that can be causing this is timeouts / slow network downloads when trying to download images using ImageIO.read(). I'm not sure what I can do to fix this issue at the moment.

ScrappingFTW has made some good improvements recently in scraping speed and I've also added a network timeout to most HTTP calls, so hopefully this should be happening much less frequently.

I'm going to keep this issue open in case anyone has ideas about possible fixes for ImageIO.read() timeing out.

**Comment by DoctorD1501** [comment] 2016-05-15 00:10
I think the problem of a scrape getting stuck is now much better than it used to be last year when this issue was created. I'm going to close this issue out and if anyone is still having problems, they can create a new issue with more specifics on what they tried exactly to create a stuck scraper.

**Closed by DoctorD1501** 2016-05-15 00:10 UTC
Labels: help wanted
