### ISSUE TITLE
Problem writing .nfo file, if character 'ö' in directoryname

### ISSUE THREAD

**Issue by nafets1** [DoctorD1501/JAVMovieScraper#173] opened 2016-11-29 23:47 UTC
The .nfo file is NOT (re-)written 
Tested using v0.2.26 under Windows on a Samba share 

Suppose, that the same Problem would occur, if other German special characters like ä ü ß 
are in the Directoryname

regards

**Comment by DoctorD1501** [comment] 2016-11-30 17:51
I'm not able to reproduce this issue. I have a directory stored on a remote computer shared via Samba. I'm using windows 10. I then put a 'ö' in the file name of the parent directory and the title of the movie (so that the movie would get the character in the new directory) and hit write and everything seemed to work OK. I got a new directory with the nfo updated and the character appearing in it.

I think I need more information: 
1) Does the problem only appear with samba shares? What about on your local disk?
2) What is the name of the file exactly including path?
3) What are the exact steps you are taking?
4) Are you using the latest version of the program?
5) Do you see any error messages appear in the program's console area? If so, what is it?

**Comment by nafets1** [comment] 2016-11-30 19:56
Thanks doctor for your answer !

Today i also can't reproduce it :-(

1.) tried it local-> OK. also on samba -> OK.
2.) the German Word 'Schönheit' was Included. Yesterday i only changed it to 'Schoenheit'.
      Thereafter the .nfo file was sucessfully written.
3.) i previously lost the Poster & Fanart files in the Directory. 
     .nfo was still available
     Tried the Button 'Write File Data', but .nfo file was not rewritten
4.) yes v0.2.26 under win8.1; Samba from libreelec v7.02
5.) sorry i didn't look. If i will Report Ägäis a Problem, i Promille i will have a look at the Output Window
      Today it locked Quote good to me


At the Moment i mostly work on a Windows Client.
When i did my other Posts (also with Similar .nfo Write Problems) i wirkend under OS X.
The Samba Server is the same.

Regards

**Comment by DoctorD1501** [comment] 2016-12-05 02:01
I'm going to close the issue as you don't seem to be able to reproduce it. Feel free to open a new one if you get some steps to reproduce the problem again.

**Closed by DoctorD1501** 2016-12-05 02:01 UTC
Labels: bug
