### ISSUE TITLE
Rename Movie File Setting Question

### ISSUE THREAD

**Issue by DarkMask100** [DoctorD1501/JAVMovieScraper#104] opened 2015-08-09 11:50 UTC
Hello,

Currently I have this option selected as it allows me to have my videos sorted by set and then by title. 

File Rename: 
< ID > - < TITLE > - < ACTORS >
Folder Rename: 
< BASEDIRECTORY >< PATHSEPERATOR >< SET >< PATHSEPERATOR ><I D > - < TITLE > - < ACTORS >< PATHSEPERATOR >

I've noticed that when using this setting and writing file data it takes around a minute or so to actually preform the process of creating the new folders and moving the files. Is this the intended function or is this a bug? Using the Move File to New Folder button creates the folder and moves the file instantly. 

The only workaround I've found is manually creating the set folder, running Move File to New Folder and then manually moving the folder to the set folder.

**Comment by DoctorD1501** [comment] 2015-08-09 15:19
If you create a text file with the same name as a movie, then rename its extension to ".avi", then scrape the file and use the write file data (with rename settings), does it still take a minute? I'm curious if it's copying the full movie file instead of just moving a small file like it would for a 0 byte movie file.

Also, do you have write trailer files enabled in the preferences? That takes a while to download the trailer file.

**Comment by DarkMask100** [comment] 2015-08-09 19:49
Hello,

I don't have write trailer files enabled. 

I created a .txt file and renamed it to one of my movies and changed the extension, and enabled Rename Movie File, it moved the file almost instantly. Took a random file (400MB) and did the same thing. Seems its copying the file and then deleting the original once its done.

**Comment by DoctorD1501** [comment] 2015-08-10 03:27
I think this is a problem with the library I am using to move files. I'm going to see if there is a better one.

**Comment by DoctorD1501** [comment] 2016-05-15 00:08
I think this got fixed by 47f4fc7bbd726b2d6ecc1f4e782a294c25aa1533 although I am not sure. I never had this problem myself, but if the problem is still occurring please update this ticket with your comment that it is still happening to you with the newest build.

**Closed by DoctorD1501** 2016-05-15 00:08 UTC
Labels: bug
