### ISSUE TITLE
Posters dont save correctly in v0.2.27-alpha

### ISSUE THREAD

**Issue by ghost** [DoctorD1501/JAVMovieScraper#188] opened 2017-04-11 18:21 UTC
Well, as the title says, posters dont save up correctly in v0.2.27-alpha. It saves like half the image and scales it up weirdly. And the fanart image file has the actual poster, so I'm guessing the program is getting fanart and poster image somehow mixed up.

 In previous version, v0.2.26-alpha this issue doesnt exist.

**Comment by Still34** [comment] 2017-04-17 09:06
Duplicate of #179

**Closed** 2018-07-07 12:05 UTC
